"""
rcon_sdk_factory_agent.py — the meta-cartridge that produces rCon
"rapplications" from a natural-language spec.

LearnNew (in the bundled rcon_agent.py) already generates *generic*
brainstem agents. This factory is rCon-aware: every cartridge it
emits is shaped for the rCon platform contract that ships in this
repo's CONSTITUTION §0:

  - One file = one rapplication
  - Optional UI skin claim (a known agent class name → desktop client
    lights up its matching renderer)
  - Optional .egg dependency declared in __manifest__.requires_eggs,
    auto-pulled from raw.githubusercontent.com on first load
  - Side-loop hook surface (so the brainstem can drive the cartridge
    headless without the user babysitting)
  - Always callable purely through chat (the Mom Test)

Per CONSTITUTION §1 the brainstem kernel + the bundled set stays
sacred — this factory is itself a bundled cartridge living in
rcon_agent.py-land, not in the kernel. It writes generated files
into agents/ which the brainstem hot-loads on the next /chat.
"""

__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@kody/rcon_sdk_factory_agent",
    "version": "0.1.0",
    "display_name": "rCon SDK Factory",
    "description": (
        "Author fully-formed rCon rapplication cartridges (agent.py + "
        "optional .egg pointers) from natural-language specs. Knows the "
        "rCon platform contract: skin claims, side-loop hooks, .egg "
        "lifecycle, Mom Test compliance."
    ),
    "author": "@kody",
    "tags": ["sdk", "factory", "rcon", "scaffold", "package-manager"],
    "category": "devtools",
    "quality_tier": "official",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
}

from agents.basic_agent import BasicAgent
import ast
import json
import os
import re
import textwrap
from datetime import datetime


# Known skin claim names the rCon desktop client looks for. Authoring a
# cartridge whose primary class matches any of these names lights up the
# iMessage skin on next /agents poll.
KNOWN_SKINS = {
    "imessage": ["TwinExpansion", "iMessageSkin", "ConsoleSkin_iMessage"],
}

# Cartridge template. Keep tight — the factory's job is to seed a
# working file; the brainstem hot-reloads on the next /chat and the
# operator can iterate.
CARTRIDGE_TEMPLATE = '''\
"""
{display_name} — generated by rcon_sdk_factory.

{description}

Generated {generated_at} for the rCon platform. Per CONSTITUTION §0:
this is a rapplication cartridge. Drop into the brainstem's agents/
to install; remove the file to uninstall. The kernel never grows
new opinions to accommodate this cartridge.
"""

__manifest__ = {manifest_repr}

from agents.basic_agent import BasicAgent
import json


class {class_name}(BasicAgent):
    """{description}"""

    def __init__(self):
        self.name = "{class_name}"
        self.metadata = {{
            "name": self.name,
            "description": (
                "{description_safe}"
            ),
            "parameters": {{
                "type": "object",
                "properties": {{
                    "action": {{
                        "type": "string",
                        "description": "What to do.",
                        "enum": {actions_json},
                    }},
                    "query": {{
                        "type": "string",
                        "description": "Natural-language input from the user.",
                    }},
                }},
                "required": [],
            }},
        }}
        super().__init__(self.name, self.metadata)
{skin_marker_block}
    def perform(self, **kwargs):
        action = (kwargs.get("action") or "{default_action}").strip().lower()
        query = kwargs.get("query") or ""

{action_dispatch}
        return json.dumps({{
            "status": "error",
            "error": f"unknown action: {{action}}",
            "available_actions": {actions_json},
        }})

{action_methods}
{side_loop_hook}
'''

SKIN_MARKER_BLOCK = """
    # Skin claim: this cartridge owns the iMessage skin on the desktop
    # client. The client polls /agents and lights up its iMessage
    # renderer only when a class with this exact name is loaded.
    SKIN_CLAIM = "imessage"
"""

SIDE_LOOP_HOOK = '''\
    def side_loop(self, base_prompt: str, max_turns: int = 8):
        """
        Optional side-loop entry. The brainstem can call this directly to
        drive the cartridge headless (per CONSTITUTION §2.3). Return a
        list of turn-dicts shaped like [{{"role": "...", "content": "..."}}, ...].
        Default: ask the brainstem to handle the base_prompt as a normal chat.
        Override for cartridges that want a richer transcript stitching.
        """
        return [{"role": "system", "content": f"side-loop entry: {base_prompt}"}]
'''


class RConSDKFactoryAgent(BasicAgent):
    def __init__(self):
        self.name = "RConSDKFactoryAgent"
        self.metadata = {
            "name": self.name,
            "description": (
                "Generate rCon rapplication cartridges (agent.py files) from a "
                "natural-language spec. Knows the rCon platform contract: skin "
                "claims, side-loop hooks, .egg lifecycle, Mom-Test compliance. "
                "Actions: 'spec' returns the manifest preview, 'scaffold' writes "
                "the file to agents/, 'validate' parses+lint-checks an existing "
                "cartridge, 'package_egg' bundles a cartridge + assets into an "
                ".egg, 'submission' formats a RAR submission for the cartridge."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ["spec", "scaffold", "validate", "package_egg", "submission"],
                        "description": "Which step of the cartridge lifecycle to run.",
                    },
                    "name": {
                        "type": "string",
                        "description": (
                            "Short cartridge name, used as the Python class. "
                            "PascalCase, no spaces (e.g. 'WeatherDeck')."
                        ),
                    },
                    "description": {
                        "type": "string",
                        "description": "What the cartridge does, in one sentence.",
                    },
                    "actions": {
                        "type": "string",
                        "description": (
                            "Comma-separated action names the cartridge will support "
                            "(e.g. 'fetch,refresh,clear')."
                        ),
                    },
                    "claims_skin": {
                        "type": "string",
                        "enum": list(KNOWN_SKINS.keys()) + [""],
                        "description": (
                            "If non-empty, the generated cartridge claims this UI skin. "
                            "Only 'imessage' is supported today; future skins land here."
                        ),
                    },
                    "requires_eggs": {
                        "type": "string",
                        "description": (
                            "Comma-separated raw.githubusercontent.com URLs to .egg "
                            "cartridges this rapplication pulls down on first run."
                        ),
                    },
                    "side_loop": {
                        "type": "boolean",
                        "description": (
                            "Include a side_loop() entry point for headless brainstem-driven "
                            "execution per CONSTITUTION §2.3."
                        ),
                    },
                    "namespace": {
                        "type": "string",
                        "description": "RAR namespace for submission (default: @kody).",
                    },
                    "filepath": {
                        "type": "string",
                        "description": "For 'validate' and 'package_egg' — path to the cartridge .py.",
                    },
                },
                "required": ["action"],
            },
        }
        super().__init__(self.name, self.metadata)

    # ── action dispatch ───────────────────────────────────────────────

    def perform(self, **kwargs):
        action = (kwargs.get("action") or "spec").strip().lower()
        try:
            if action == "spec":
                return self._spec(**kwargs)
            if action == "scaffold":
                return self._scaffold(**kwargs)
            if action == "validate":
                return self._validate(**kwargs)
            if action == "package_egg":
                return self._package_egg(**kwargs)
            if action == "submission":
                return self._submission(**kwargs)
        except Exception as e:
            return json.dumps({"status": "error", "action": action, "error": str(e)})
        return json.dumps({"status": "error", "error": f"unknown action: {action}"})

    # ── spec / scaffold ───────────────────────────────────────────────

    def _build_class_name(self, raw_name: str) -> str:
        if not raw_name:
            raise ValueError("name is required")
        # PascalCase the name; drop non-identifier chars.
        parts = re.split(r"[^A-Za-z0-9]+", raw_name.strip())
        cls = "".join(p[:1].upper() + p[1:] for p in parts if p)
        if not cls or not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", cls):
            raise ValueError(f"can't derive a Python class name from {raw_name!r}")
        return cls

    def _build_actions(self, raw: str) -> list[str]:
        actions = [a.strip() for a in (raw or "").split(",") if a.strip()]
        return actions or ["run"]

    def _manifest_for(self, *, name: str, description: str, namespace: str,
                      requires_eggs: list[str], skin: str) -> dict:
        slug = re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_")
        tags = ["rcon", "rapplication"]
        if skin:
            tags.append(f"skin:{skin}")
        m = {
            "schema": "rapp-agent/1.0",
            "name": f"@{namespace.lstrip('@')}/{slug}",
            "version": "0.1.0",
            "display_name": name,
            "description": description,
            "author": f"@{namespace.lstrip('@')}",
            "tags": tags,
            "category": "rapplication",
            "quality_tier": "community",
            "platform": "rcon",
            "requires_env": [],
            "dependencies": ["@rapp/basic_agent"],
        }
        if requires_eggs:
            m["requires_eggs"] = requires_eggs
        if skin:
            m["claims_skin"] = skin
        return m

    def _render_cartridge(self, *, class_name: str, description: str,
                          actions: list[str], skin: str, side_loop: bool,
                          manifest: dict, display_name: str) -> str:
        desc_safe = description.replace('"', '\\"')
        actions_json = json.dumps(actions)

        # Skin marker: a class-level constant the desktop client checks via /agents
        # when it can't rely solely on the class NAME (e.g. when the user gave the
        # cartridge a domain-specific name but still wants the iMessage skin).
        skin_marker = SKIN_MARKER_BLOCK if skin == "imessage" else ""

        # Action dispatch — one elif per declared action that returns a stub.
        dispatch_lines, method_blocks = [], []
        for i, act in enumerate(actions):
            method = "_act_" + re.sub(r"[^a-z0-9_]+", "_", act.lower()).strip("_")
            kw = "if" if i == 0 else "elif"
            dispatch_lines.append(f"        {kw} action == \"{act}\":")
            dispatch_lines.append(f"            return self.{method}(query=query, **kwargs)")
            method_blocks.append(textwrap.indent(
                f"def {method}(self, query: str = \"\", **kwargs):\n"
                f"    # TODO: real {act} behavior. The brainstem will hand you a\n"
                f"    # natural-language `query`; return a JSON string the user\n"
                f"    # can read in chat (the Mom Test).\n"
                f"    return json.dumps({{\"status\": \"ok\", \"action\": \"{act}\", \"echo\": query}})\n",
                "    ",
            ))

        action_dispatch = "\n".join(dispatch_lines)
        action_methods = "\n".join(method_blocks)
        side_loop_block = SIDE_LOOP_HOOK if side_loop else ""

        return CARTRIDGE_TEMPLATE.format(
            display_name=display_name,
            description=description,
            generated_at=datetime.utcnow().isoformat() + "Z",
            manifest_repr=repr(manifest),
            class_name=class_name,
            description_safe=desc_safe,
            actions_json=actions_json,
            default_action=actions[0],
            skin_marker_block=skin_marker,
            action_dispatch=action_dispatch,
            action_methods=action_methods,
            side_loop_hook=side_loop_block,
        )

    def _spec(self, **kw):
        cls = self._build_class_name(kw.get("name", ""))
        desc = (kw.get("description") or "").strip()
        if not desc:
            return json.dumps({"status": "error", "error": "description is required"})
        skin = (kw.get("claims_skin") or "").strip().lower()
        if skin and skin not in KNOWN_SKINS:
            return json.dumps({"status": "error", "error": f"unknown skin {skin!r}; known: {list(KNOWN_SKINS.keys())}"})
        eggs = [e.strip() for e in (kw.get("requires_eggs") or "").split(",") if e.strip()]
        actions = self._build_actions(kw.get("actions", ""))
        ns = (kw.get("namespace") or "@kody").lstrip("@")
        manifest = self._manifest_for(
            name=cls, description=desc, namespace=ns,
            requires_eggs=eggs, skin=skin,
        )
        return json.dumps({
            "status": "ok",
            "action": "spec",
            "class_name": cls,
            "manifest": manifest,
            "actions": actions,
            "claims_skin": skin or None,
            "side_loop": bool(kw.get("side_loop")),
            "next_step": "Re-run with action='scaffold' to write the cartridge to agents/.",
        }, indent=2)

    def _scaffold(self, **kw):
        cls = self._build_class_name(kw.get("name", ""))
        desc = (kw.get("description") or "").strip()
        if not desc:
            return json.dumps({"status": "error", "error": "description is required"})
        skin = (kw.get("claims_skin") or "").strip().lower()
        eggs = [e.strip() for e in (kw.get("requires_eggs") or "").split(",") if e.strip()]
        actions = self._build_actions(kw.get("actions", ""))
        ns = (kw.get("namespace") or "@kody").lstrip("@")
        manifest = self._manifest_for(
            name=cls, description=desc, namespace=ns,
            requires_eggs=eggs, skin=skin,
        )
        code = self._render_cartridge(
            class_name=cls, description=desc, actions=actions,
            skin=skin, side_loop=bool(kw.get("side_loop")),
            manifest=manifest, display_name=cls,
        )

        # Parse-check before writing — never ship a cartridge that won't
        # load. CONSTITUTION §0: every skin/cartridge must be authored to spec.
        try:
            ast.parse(code)
        except SyntaxError as e:
            return json.dumps({
                "status": "error", "error": f"generated cartridge failed parse-check: {e}",
                "code": code,
            })

        agents_dir = os.path.dirname(os.path.abspath(__file__))
        slug = manifest["name"].split("/")[-1]
        filepath = os.path.join(agents_dir, f"{slug}_agent.py")
        with open(filepath, "w") as fh:
            fh.write(code)

        return json.dumps({
            "status": "ok",
            "action": "scaffold",
            "filepath": filepath,
            "class_name": cls,
            "manifest_name": manifest["name"],
            "hint": (
                "Cartridge written. The brainstem will hot-load it on the next "
                "/chat. Edit the _act_* method bodies to wire up real behavior."
            ),
        }, indent=2)

    # ── validate ──────────────────────────────────────────────────────

    def _validate(self, **kw):
        filepath = kw.get("filepath") or ""
        if not filepath or not os.path.isfile(filepath):
            return json.dumps({"status": "error", "error": "filepath required and must exist"})
        with open(filepath, "r") as fh:
            src = fh.read()
        problems = []
        try:
            tree = ast.parse(src)
        except SyntaxError as e:
            return json.dumps({"status": "error", "error": f"parse failed: {e}"})

        # Must define at least one BasicAgent subclass with a perform method.
        classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]
        agent_classes = []
        for c in classes:
            bases = [b.id for b in c.bases if isinstance(b, ast.Name)]
            if "BasicAgent" in bases:
                agent_classes.append(c)
        if not agent_classes:
            problems.append("no BasicAgent subclass found — cartridge can't be loaded by the brainstem")

        for c in agent_classes:
            methods = {n.name for n in c.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}
            if "perform" not in methods:
                problems.append(f"class {c.name} is missing perform() — brainstem won't expose it")

        manifest_node = next(
            (n for n in tree.body
             if isinstance(n, ast.Assign)
             and any(isinstance(t, ast.Name) and t.id == "__manifest__" for t in n.targets)),
            None,
        )
        if not manifest_node:
            problems.append("no __manifest__ — required for RAR submission")

        return json.dumps({
            "status": "ok" if not problems else "warn",
            "action": "validate",
            "filepath": filepath,
            "agent_classes": [c.name for c in agent_classes],
            "problems": problems,
            "ok_to_submit": not problems,
        }, indent=2)

    # ── package_egg ───────────────────────────────────────────────────

    def _package_egg(self, **kw):
        """
        Bundle the cartridge + any sibling assets the user wants shipped
        with it (sample data, soul.md, etc) into an .egg (zip) so the
        whole rapplication ships as one file.
        """
        import zipfile
        filepath = kw.get("filepath") or ""
        if not filepath or not os.path.isfile(filepath):
            return json.dumps({"status": "error", "error": "filepath required and must exist"})
        cart_dir = os.path.dirname(os.path.abspath(filepath))
        cart_name = os.path.splitext(os.path.basename(filepath))[0]
        egg_path = os.path.join(cart_dir, f"{cart_name}.egg")
        members = [filepath]
        # Pick up any sibling rapp-payload files explicitly tagged with
        # cart_name as prefix (e.g. weather_deck_data.json).
        for f in os.listdir(cart_dir):
            full = os.path.join(cart_dir, f)
            if full == filepath: continue
            if f.startswith(cart_name + "_") and os.path.isfile(full):
                members.append(full)
        with zipfile.ZipFile(egg_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for m in members:
                zf.write(m, os.path.basename(m))
        return json.dumps({
            "status": "ok", "action": "package_egg",
            "egg": egg_path, "members": [os.path.basename(m) for m in members],
            "hint": "Hand this .egg to anyone with a brainstem — they hatch it and the rapplication installs.",
        }, indent=2)

    # ── submission ────────────────────────────────────────────────────

    def _submission(self, **kw):
        """
        Format a RAR submission for the cartridge. The submission itself
        (a `gh issue create` call against kody-w/RAR) is left to the
        RARRemoteAgent / the user — this action just produces the payload.
        """
        filepath = kw.get("filepath") or ""
        if not filepath or not os.path.isfile(filepath):
            return json.dumps({"status": "error", "error": "filepath required and must exist"})
        with open(filepath, "r") as fh:
            code = fh.read()
        # Pull the manifest out of the source — RAR's pipeline reads it.
        tree = ast.parse(code)
        manifest_node = next(
            (n for n in tree.body
             if isinstance(n, ast.Assign)
             and any(isinstance(t, ast.Name) and t.id == "__manifest__" for t in n.targets)),
            None,
        )
        manifest_repr = "<no __manifest__>"
        if manifest_node is not None:
            try:
                manifest_repr = ast.literal_eval(manifest_node.value)
            except Exception:
                manifest_repr = ast.unparse(manifest_node.value)
        return json.dumps({
            "status": "ok",
            "action": "submission",
            "filename": os.path.basename(filepath),
            "manifest": manifest_repr,
            "issue_title": f"[RAR] submit_agent: {os.path.basename(filepath)}",
            "issue_body_template": (
                "## Submission\n\n"
                "**Manifest:**\n```json\n" + json.dumps(manifest_repr, indent=2) + "\n```\n\n"
                "**Source:**\n```python\n" + code + "\n```\n"
            ),
            "next_step": (
                "Pass this body to RARRemoteAgent.perform(action='submit', code=<source>) "
                "to file the GitHub issue against kody-w/RAR. Or copy/paste manually at "
                "https://github.com/kody-w/RAR/issues/new."
            ),
        }, indent=2)
