"""
CardSmith Agent — Forges trading cards for AI agents.

Turn any agent into a collectible card with stats, abilities, and art.
The smith that forges the cards is itself a card.

This is the .py.card format — the complete agent+card package.
"""

try:
    from basic_agent import BasicAgent
except ModuleNotFoundError:
    from agents.basic_agent import BasicAgent

# ── Agent Manifest ──
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@borg/cardsmith_agent",
    "version": "1.0.0",
    "display_name": "CardSmith",
    "description": "Forges trading cards for AI agents. Turn any agent into a collectible card with stats, abilities, and art.",
    "author": "Howard",
    "tags": ["productivity", "cards", "visualization", "trading-cards", "sneakernet"],
    "category": "productivity",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic-agent"],
}

# ── Card Shell (Howard-compatible) ──
# Generated by: CardSmith forge action (self-referential)
# This card forges other cards. It is the origin point.
__card__ = {
    "name": "CardSmith",
    "title": "The Forgemaster",
    "mana_cost": "{2}{R}{W}",
    "colors": ["R", "W"],
    "type_line": "Legendary Creature \u2014 Agent Artificer",
    "rarity": "mythic",
    "power": 4,
    "toughness": 6,
    "abilities": [
        {
            "keyword": "Forge",
            "cost": "{T}",
            "text": "Target agent becomes a trading card. Generate stats, abilities, art, and flavor text from its manifest.",
        },
        {
            "keyword": "Mass Production",
            "cost": "{3}{T}",
            "text": "Forge cards for all agents in the registry. Each card is deterministic \u2014 same agent, same card, always.",
        },
        {
            "keyword": "Howard's Touch",
            "cost": "",
            "text": "Cards forged by CardSmith that match the original 13 use Howard's hand-crafted art and stats instead of procedural generation.",
        },
    ],
    "flavor_text": "\"Every agent deserves a card. Every card deserves to be held.\" \u2014Howard, on why sneakernet matters",
    "avatar_svg": '<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"><defs><radialGradient id="bg-cs"><stop offset="0%" stop-color="#2a1a0a"/><stop offset="100%" stop-color="#0a0804"/></radialGradient><filter id="glow-cs"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="200" height="200" fill="url(#bg-cs)"/><g filter="url(#glow-cs)"><polygon points="100,30 130,50 130,90 100,110 70,90 70,50" fill="none" stroke="#ff9800" stroke-width="2" opacity="0.7"/><rect x="60" y="110" width="80" height="50" rx="4" fill="none" stroke="#ef6c00" stroke-width="2" opacity="0.6"/><line x1="60" y1="125" x2="140" y2="125" stroke="#ff9800" stroke-width="1" opacity="0.3"/><line x1="60" y1="140" x2="140" y2="140" stroke="#ff9800" stroke-width="1" opacity="0.3"/><circle cx="100" cy="70" r="20" fill="#ff9800" opacity="0.15"/><circle cx="100" cy="70" r="10" fill="#ef6c00" opacity="0.3"/><circle cx="100" cy="70" r="4" fill="#ffb74d" opacity="0.9"/><line x1="100" y1="50" x2="100" y2="30" stroke="#ffb74d" stroke-width="1.5" opacity="0.5"/><line x1="80" y1="60" x2="70" y2="50" stroke="#ff9800" stroke-width="1" opacity="0.4"/><line x1="120" y1="60" x2="130" y2="50" stroke="#ff9800" stroke-width="1" opacity="0.4"/><circle cx="75" cy="130" r="3" fill="#ff9800" opacity="0.4"/><circle cx="100" cy="130" r="3" fill="#ef6c00" opacity="0.5"/><circle cx="125" cy="130" r="3" fill="#ff9800" opacity="0.4"/></g></svg>',
    "set_code": "HOLO",
    "artist": "Howard",
}


# ── Agent Implementation ──

class CardSmithAgent(BasicAgent):
    """Forges Magic: The Gathering style trading cards for brainstem agents."""

    def __init__(self):
        self.name = "CardSmith"
        self.metadata = {
            "name": "CardSmith",
            "description": "Forges trading cards for AI agents.",
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ["forge", "forge_all", "gallery"],
                        "description": "forge: single card, forge_all: all cards, gallery: link",
                    },
                    "agent_name": {
                        "type": "string",
                        "description": "Agent name to forge (required for forge action)",
                    },
                },
                "required": ["action"],
            },
        }
        super().__init__()

    def perform(self, **kwargs):
        action = kwargs.get("action", "gallery")
        if action == "forge":
            name = kwargs.get("agent_name", "")
            if not name:
                return "Provide agent_name to forge a card."
            return f"Card forged for {name}. View it in the Agent Store cards tab."
        elif action == "forge_all":
            return "All cards forged. Run generate_holo_cards.py to regenerate the full set."
        return "Gallery: open the Agent Store and switch to Cards tab."
